[project]
name = "masta"
version = "2.0.0"
description = "automate the management of downloading and installing python packages from github to local pip"

[project.scripts]
something = "masta.cli:something"
